version = 11
name = "add_ruby"
description = "Get to know the Fastly Compute@Edge environment with a basic starter that demonstrates routing, simple synthetic responses and overriding caching rules."
authors = ["xgu+ecp@fastly.com"]
language = "rust"
service_id = "0aDEGwC7jHSwWBe9FfYR6A"
